image: "rust:latest"
cache:
  paths:
    - target/

stages:
  - test
  - build

test:
  stage: test
  script:
    - rustc --version && cargo --version
    # - cargo test --all --verbose

linux-x86_64:
  stage: build
  artifacts:
    paths:
      - target/release/nzb
  script:
    - cargo build --release
# windows-x86_64:
#   stage: build
#   artifacts:
#     paths:
#       - target/x86_64-pc-windows-gnu/release/nzb.exe
#   before_script:
#     - rustup toolchain install stable-x86_64-pc-windows-gnu
#   script:
#     - cargo build --release --target x86_64-pc-windows-gnu
