image: "sseemayer/rust-musl-builder-mingw:latest"

cache:
  paths:
    - target/

stages:
  - test
  - build

test:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --all --verbose

x86_64-unknown-linux-gnu:
  stage: build

  artifacts:
    paths:
      - target/release/nzb

  script:
    - cargo build --release

x86_64-pc-windows-gnu:
  stage: build

  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/nzb.exe

  script:
    - cargo build --release --target x86_64-pc-windows-gnu
