[package]
name = "nzb"
version = "0.1.2"
authors = ["reisub0 <reisub0@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "^1.0.5"
docopt = "^1"
prettytable-rs = "^0.8"
reqwest = "^0.9.11"
serde = { version = "^1", features=["derive"]}
serde_derive = "^1"
serde_json = "^1"
skim = "^0.5.5"
